### PR TITLE
Issue #168: Stopped error messages from being propogated

### LINKED ISSUE #168: Improve error handling
Many errors don't appear to be handled, or at least the error message needs a lot more context, eg

```
62eb9efa694a:1021 local_smartmedia: Processing media file metadata
Incorrect BOM value
Error reading comment frame, skipped
```

```
[h264 @ 0x558d3dbdc2c0] A non-intra slice in an IDR NAL unit.
[h264 @ 0x558d3dbdc2c0] decode_slice_header error
```

We'd want:

1) more context of the task, file, etc because these get interleaved in cron in among other log lines
2) what type of error we got, 
3) should this bung file be flagged somehow in the db so its not retrying the same file over and over

### PR DESCRIPTION
**Pull request by Peterburnett**
Closes #168 . This patch does not currently flag files from being rerun, due to the possibility of a temporary issue, and it would require larger DB changes to support this for little gain

### CODE REVIEW

File: classes/ffprobe.php [hunk 1]
```diff
@@ -145,12 +145,31 @@ public function get_media_metadata(\stored_file $file) : array {
...
+        $errs = file_get_contents($errfile);
+        unlink($errfile);
+        if (!empty($errs)) {
+            $exit = true;
+        }
+
+        if ($rawresults) { // We got a result, check it for sanity
             $resultobject = json_decode($rawresults);
+            if ($resultobject == []) {
+                // FFprobe must have errored and returned empty JSON.
```
Comment (brendanheywood) [inline classes/ffprobe.php:164]: is there also a case where $errs is empty, but the command returned something which wasn't json? in which case maybe dump the malformed json into the $errs. might never happen but can't hurt
